name: Build, Push, and Expose Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-expose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Test Docker container 
        run: | 
          curl http://localhost:8080
 
